[theme]
theme = "slick"

[icons]
icons = "awesome6"

[[block]]
block = "battery"

[[block]]
block = "temperature"

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:2) "

[[block]]
block = "cpu"

[[block]]
block = "load"

[[block]]
block = "sound"

[[block]]
block = "time"
